FROM python:3.11

WORKDIR /usr/src/app
COPY . .
# INSTALL GSAM
RUN git clone https://github.com/IDEA-Research/Grounded-Segment-Anything
WORKDIR  /usr/src/app/Grounded-Segment-Anything
RUN pip install  -r requirements.txt
WORKDIR /usr/src/app/Grounded-Segment-Anything/GroundingDINO
RUN pip install  .
WORKDIR /usr/src/app/Grounded-Segment-Anything/segment_anything
RUN pip install  .
WORKDIR /usr/src/app
RUN apt-get update && apt-get install -y python3-opencv
RUN pip install opencv-python

RUN pip install torch torchvision

WORKDIR /usr/src/app
RUN pip install  -r requirements.txt
RUN wget -q https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth

EXPOSE 7860
ENV GRADIO_SERVER_NAME="0.0.0.0"

CMD ["python", "app.py"]