FROM pytorch/pytorch:2.3.1-cuda11.8-cudnn8-devel


WORKDIR /usr/src/app
COPY . .
RUN pip install --upgrade pip setuptools wheel

RUN pip install torch torchvision
RUN python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'


RUN pip install  -r requirements.txt

EXPOSE 7860
ENV GRADIO_SERVER_NAME="0.0.0.0"

CMD ["python", "app.py"]