name: Build & publish RB-IBDM images
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  USERNAME: ${{ github.repository_owner }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          
          - dockerfile: ./gradio-detectron/Dockerfile
            image: ghcr.io/kiiwee/rb-ibdm-gradio-detectron
            context: ./gradio-detectron

          - dockerfile: ./gradio-yolo/Dockerfile
            image: ghcr.io/kiiwee/rb-ibdm-gradio-yolo
            context: ./gradio-yolo

          - dockerfile: ./gradio-yolo/Dockerfile.gpu
            image: ghcr.io/kiiwee/rb-ibdm-gradio-yolo-gpu
            context: ./gradio-yolo

          - dockerfile: ./gradio-fulldemo/Dockerfile
            image: ghcr.io/kiiwee/rb-ibdm-gradio-full-demo
            context: ./gradio-fulldemo
        
          - dockerfile: ./gradio-gsl/Dockerfile.cpu
            image: ghcr.io/kiiwee/rb-ibdm-gradio-gsl
            context: ./gradio-gsl
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
        with:
          cosign-release: 'v2.2.4'

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Log in to the Container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0

        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0

        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image Drill4Net.Agent.Service
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ${{ matrix.context }}

          platforms: linux/amd64,linux/arm64

          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}